export interface IElementHistory {
    element: number;
    fixture: number;
    opponentTeam: number;
    totalPoints: number;
    wasHome: boolean;
    kickoffTime: string;
    teamHScore: number;
    teamAScore: number;
    round: number;
    minutes: number;
    goalsScored: number;
    assists: number;
    cleanSheets: number;
    goalsConceded: number;
    ownGoals: number;
    penaltiesSaved: number;
    penaltiesMissed: number;
    yellowCards: number;
    redCards: number;
    saves: number;
    bonus: number
    bps: number;
    influence: string;
    creativity: string;
    threat: string;
    ictIndex: string;
    value: number;
    transfersBalance: number;
    selected: number;
    transfersIn: number;
    transfersOut: number;
}
